### ISSUE TITLE
Header issues with node v13

### ISSUE THREAD

**Issue by stanleynguyen** [xendit/xendit-node#12]
```bash
FetchError: request to https://api.xendit.co/available_disbursements_banks failed, reason: Parse Error: Invalid header value char
    at ClientRequest.<anonymous> (/Users/stanleynguyen/Documents/Projects/xendit-node/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:219:5)
    at TLSSocket.socketOnData (_http_client.js:474:9)
    at TLSSocket.emit (events.js:219:5)
    at addChunk (_stream_readable.js:332:12)
    at readableAddChunk (_stream_readable.js:307:11)
    at TLSSocket.Readable.push (_stream_readable.js:241:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:185:23) {
  message: 'request to https://api.xendit.co/available_disbursements_banks failed, reason: Parse Error: Invalid header value char',
  type: 'system',
  errno: 'HPE_INVALID_HEADER_TOKEN',
  code: 'HPE_INVALID_HEADER_TOKEN'
}
```

**Comment by stanleynguyen** [comment]
Workaround https://stackoverflow.com/questions/36628420/nodejs-request-hpe-invalid-header-token/36655326

**Comment by stanleynguyen** [comment]
Resolved with Imperva disabling the invalid header defence mechanism
https://xendit.slack.com/archives/C3HLBHX4N/p1576305181000900?thread_ts=1576212003.366800&cid=C3HLBHX4N
