### ISSUE TITLE
Header issue with node v12

### ISSUE THREAD

**Issue by stanleynguyen** [xendit/xendit-node#14]
```
FetchError: request to https://api.xendit.co/available_virtual_account_banks failed, reason: Parse Error: Invalid header value char
    at ClientRequest.<anonymous> (/Users/stanleynguyen/Documents/Projects/xendit-node/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketOnData (_http_client.js:463:9)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  message: 'request to https://api.xendit.co/available_virtual_account_banks failed, reason: Parse Error: Invalid header value char',
  type: 'system',
  errno: 'HPE_INVALID_HEADER_TOKEN',
  code: 'HPE_INVALID_HEADER_TOKEN'
}
```

**Comment by stanleynguyen** [comment]
v12 doesn't allow monkey patching hence can't be fixed with `http-parser-js`

**Comment by stanleynguyen** [comment]
Resolved with Imperva disabling the invalid header defence mechanism
https://xendit.slack.com/archives/C3HLBHX4N/p1576305181000900?thread_ts=1576212003.366800&cid=C3HLBHX4N
